config/routes.rb
Rails.application.routes.draw do

  
  resources :charges, only: [:new, :create]
  resources :line_items
  get '/products/:id/repairs', :to => 'products#repairs'
  get '/products/estimate_price', :to => 'products#estimate_price'
  get 'search/index'
  devise_for :users
  get 'user', to: 'users#show', as: 'myorders'
  resources :products
  resources :repairables
  resources :search, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'send/:id', to: 'pages#sendForm'
  get 'sales', to: 'sales#index'
  get '/admin/import', :to => 'admin#newimport'
  post '/admin/import', :to => 'admin#createimport'
  get '/admin/orders', :to => 'admin#orders'
  get '/admin/orders/:id', :to => 'admin#order'

  resources :app_setting, only: [:edit, :update, :show]

  get 'cart', to: 'carts#show', as: 'mycart'
  
  resources :orders, only: [:show]

end

app/models/app_setting.rb
class AppSetting < ApplicationRecord
    # The "singleton_guard" column is a unique column which must always be set to '0'
    # This ensures that only one AppSettings row is created
    validates_inclusion_of :singleton_guard, :in => [0]
    
    def self.instance
        first_or_create!(singleton_guard: 0)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
      current_item = line_items.find_by(product_id: product.id)
  
      if current_item
        current_item.increment(:quantity)
      else
        current_item = line_items.build(product_id: product.id)
      end
      current_item
    end
  
    def total_price
      line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  
  def total_price
    product.price * quantity.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    belongs_to :user, optional: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
require 'csv'
class Product < ApplicationRecord
    has_one_attached :productimage
    has_many :line_items
    has_many :order_items
    has_many :repairables
    accepts_nested_attributes_for :repairables

    # validates :name, :manufacturer, :model, :description, :quantity, :price, presence: true
    validates :model, uniqueness: true

    include PgSearch::Model
    pg_search_scope :search, against: [:name, :model, :manufacturer]

    before_destroy :not_referenced_by_any_line_item
    belongs_to :user, optional: true

    def self.import(file)
      CSV.foreach(file.path, headers:true) do |row|
        if !Product.find_by(model: row[2])
          product = Product.new
          product.name = row[0]
          product.manufacturer = row[1]
          product.model = row[2]
          product.description = row[3]
          product.quantity = row[4]
          product.price = row[5]
          product.is_repairable = row[6]
          product.base_price = row[7]
          product.save
        end
      end
    end

    private
  
     def not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line items present')
        throw :abort
      end
     end
end

app/models/repairable.rb
class Repairable < ApplicationRecord
    belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders
end

app/controllers/repairables_controller.rb
class RepairablesController < ApplicationController
  before_action :set_repairable, only: [:show, :edit, :update, :destroy]

  # GET /repairables
  # GET /repairables.json
  def index
    # binding.pry
    if not params[:search].present?
      @repairables = Product.where(:is_repairable => true)
    else
      @repairables = Product.where(:is_repairable => true).search(params[:search])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @repairables.to_json(:include => :repairables), status: :ok}
    end
    # render :json => @repairables, status: :ok
  end

  # GET /repairables/1
  # GET /repairables/1.json
  def show
  end

  # GET /repairables/new
  def new
    @repairable = Repairable.new
  end

  # GET /repairables/1/edit
  def edit
  end

  # POST /repairables
  # POST /repairables.json
  def create
    @repairable = Repairable.new(repairable_params)

    respond_to do |format|
      if @repairable.save
        format.html { redirect_to @repairable, notice: 'Repairable was successfully created.' }
        format.json { render :show, status: :created, location: @repairable }
      else
        format.html { render :new }
        format.json { render json: @repairable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repairables/1
  # PATCH/PUT /repairables/1.json
  def update
    respond_to do |format|
      if @repairable.update(repairable_params)
        format.html { redirect_to @repairable, notice: 'Repairable was successfully updated.' }
        format.json { render :show, status: :ok, location: @repairable }
      else
        format.html { render :edit }
        format.json { render json: @repairable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairables/1
  # DELETE /repairables/1.json
  def destroy
    @repairable.destroy
    respond_to do |format|
      format.html { redirect_to repairables_url, notice: 'Repairable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repairable
      @repairable = Repairable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def repairable_params
      params.fetch(:repairable, {})
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/app_setting_helper.rb
module AppSettingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/repairables_helper.rb
module RepairablesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/repairables/_form.html.erb
<%= form_with(model: repairable, local: true) do |form| %>
  <% if repairable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repairable.errors.count, "error") %> prohibited this repairable from being saved:</h2>

      <ul>
        <% repairable.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/repairables/_search.html.erb
<setion class="row">
  <h1>Search for repairables</h1>
</setion> 

<setion class="row">
<%= form_tag repairables_path, url: repairables_path, method: :get do %>
  <%=text_field_tag :search %>
  <%=submit_tag 'search', name: nil %>
<% end %>
</setion> 

<%# <%= form_for , url: repairables_path, method: :get, class: 'form-inline' do |form| %>
  <%# <%= form.text_field :query, value: params[:search].presence && params[:search][:query] %> 
  <%# <%= form.text_field :search, input_html: {value: ""} %>
  <%# <%= form.submit "Search", class: "btn btn-sm btn-primary", name: nil %>
<%# <% end %> 
<%# <input type="text" name="query" id="query" placeholder="I want to find..">
<input type="submit" name="commit" value="Search" class="btn btn-default"> %>

<setion class="row">

<% unless @repairables.nil? %>
  <% if @repairables.empty? %>
    <h2>No repairables found matching your query.</h2>
  <% else %>
    <h2>Results</h2>

    <table style="width: 100%;">
      <thead>
         <tr>
           <th>Model</th>
           <th>Manufacturer</th>
           <th>Model Year</th>
         </tr>
      </thead>

      <tbody>
        <% @repairables.each do |repairable| %>
          <tr>
            <td><%= repairable.model %></td>
            <td><%= repairable.manufacturer %></td>
            <td><%= link_to 'View', product_path(repairable.id) %></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  <% end %>
<% end %>
</setion> 

app/views/repairables/edit.html.erb
<h1>Editing Repairable</h1>

<%= render 'form', repairable: @repairable %>

<%= link_to 'Show', @repairable %> |
<%= link_to 'Back', repairables_path %>

app/views/repairables/index.html.erb
<div id="react-container">
<%= javascript_pack_tag 'indexRepair' %>
</div>

app/views/repairables/new.html.erb
<h1>New Repairable</h1>

<%= render 'form', repairable: @repairable %>

<%= link_to 'Back', repairables_path %>

app/views/repairables/search.html.erb
<p id="notice"><%= notice %></p>

<%= render "search" %>
<%# <h1>Repairables</h1> %>
<%# <p>
  Press <%= link_to 'here', search_repairables_path % to search for posts. </p>  %>

<%# <table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repairables.each do |repairable| %>
      <%# <tr> %>
        <%# <td> %>
      <%# </tr> %>
    <%# <% end %> 
  <%# </tbody> %>
<%# </table> %>

<%# <br>  %>

<%# <%= link_to 'Show', repairable %>
<%# <%= link_to 'Edit', edit_repairable_path(repairable) %>
<%# <%= link_to 'Destroy', repairable, method: :delete, data: { confirm: 'Are you sure?' } %> 
<%# <%= link_to 'New Repairable', new_repairable_path %>

app/views/repairables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_repairable_path(@repairable) %> |
<%= link_to 'Back', repairables_path %>