config/routes.rb
Rails.application.routes.draw do

  
  resources :charges, only: [:new, :create]
  resources :line_items
  get '/products/:id/repairs', :to => 'products#repairs'
  get '/products/estimate_price', :to => 'products#estimate_price'
  get 'search/index'
  devise_for :users
  get 'user', to: 'users#show', as: 'myorders'
  resources :products
  resources :repairables
  resources :search, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'send/:id', to: 'pages#sendForm'
  get 'sales', to: 'sales#index'
  get '/admin/import', :to => 'admin#newimport'
  post '/admin/import', :to => 'admin#createimport'
  get '/admin/orders', :to => 'admin#orders'
  get '/admin/orders/:id', :to => 'admin#order'

  resources :app_setting, only: [:edit, :update, :show]

  get 'cart', to: 'carts#show', as: 'mycart'
  
  resources :orders, only: [:show]

end

app/models/app_setting.rb
class AppSetting < ApplicationRecord
    # The "singleton_guard" column is a unique column which must always be set to '0'
    # This ensures that only one AppSettings row is created
    validates_inclusion_of :singleton_guard, :in => [0]
    
    def self.instance
        first_or_create!(singleton_guard: 0)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
      current_item = line_items.find_by(product_id: product.id)
  
      if current_item
        current_item.increment(:quantity)
      else
        current_item = line_items.build(product_id: product.id)
      end
      current_item
    end
  
    def total_price
      line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  
  def total_price
    product.price * quantity.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    belongs_to :user, optional: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
require 'csv'
class Product < ApplicationRecord
    has_one_attached :productimage
    has_many :line_items
    has_many :order_items
    has_many :repairables
    accepts_nested_attributes_for :repairables

    # validates :name, :manufacturer, :model, :description, :quantity, :price, presence: true
    validates :model, uniqueness: true

    include PgSearch::Model
    pg_search_scope :search, against: [:name, :model, :manufacturer]

    before_destroy :not_referenced_by_any_line_item
    belongs_to :user, optional: true

    def self.import(file)
      CSV.foreach(file.path, headers:true) do |row|
        if !Product.find_by(model: row[2])
          product = Product.new
          product.name = row[0]
          product.manufacturer = row[1]
          product.model = row[2]
          product.description = row[3]
          product.quantity = row[4]
          product.price = row[5]
          product.is_repairable = row[6]
          product.base_price = row[7]
          product.save
        end
      end
    end

    private
  
     def not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line items present')
        throw :abort
      end
     end
end

app/models/repairable.rb
class Repairable < ApplicationRecord
    belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/app_setting_helper.rb
module AppSettingHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<p>Admin control panel stub</p>

app/views/admin/new_import.html.erb
<h2>Bulk Product Upload</h2>
<small class="text-muted">Want to create just one new product? <a href="/products/new">Try adding a single one instead.</a></small><br /><br />

<div>
Upload a .csv file containing rows of product data to create many new products at once.  Download and view a sample .csv to make sure you use the right formatting.
</div>
<br />

<div class="container">
<%= form_tag admin_import_path, multipart: true do %>
    <div class="form-group">
        <%= file_field_tag :file, class: "form-control" %><br />
        <%= submit_tag "Upload CSV", class: "btn btn-primary" %>
    </div>
<% end %>
</div>

app/views/admin/order.html.erb
<h2>Summary for Order <%= @order.id %> by <%= @order.email %></h2>

<br />
<br />
<table class="table">
<thead class="thead-dark">
<tr>
<th scope="col">Product Name</th>
<th scope="col">Price</th>
</tr>
</thead>
<% @order.order_items.each do |item| %>
    <tr>
    <th scope="col"><%= item.product.name %></th>
    <th scope="col">$<%= '%.2f' % item.product.price.to_i %></th>
    </tr>
<% end %>
<th scope="col">Total</th>
<th scope="col">$<%= '%.2f' % @order.total.to_i %></th>
</table>

app/views/admin/orders.html.erb
<h2>All Orders</h2>

<% if @orders.length === 0 %>
    No orders have been made.
<% else %>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Order Number</th>
                <th scope="col">Order Date</th>
                <th scope="col">Customer Email</th>
                <th scope="col">Order Total</th>
            </tr>
        </thead>
    <% @orders.each do |order| %>
        <tr>
            <th scope="col"><a href=<%= "/admin/orders/" + order.id.to_s %>><%= order.id %></a></th>
            <th scope="col"><%= order.created_at %></th>
            <th scope="col"><%= mail_to order.email %></th>
            <th scope="col">$<%= '%.2f' % order.total %></th>
        </tr>
    <% end %>
    </table>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"></circle><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"></path></svg>
      <small class="d-block mb-3 text-muted">© 2017-2020</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Business</a></li>
        <li><a class="text-muted" href="#">Education</a></li>
        <li><a class="text-muted" href="#">Government</a></li>
        <li><a class="text-muted" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/products">Buy a Device</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/repairables">Repair My Device</a>
      </li>
      <li class="nav-item">
        <%= link_to "Sell My Device", sales_path, method: :get, :class => 'nav-link'%>
      </li>
    </ul>
  </div>  
  <div class="mx-auto order-0">
    <a class="navbar-brand mx-auto" href="/">Somsaem</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
    <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
    <ul class="navbar-nav ml-auto">
      <% if current_user && current_user.admin? %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="/products/new">Add Single Product</a>
              <a class="dropdown-item" href="/admin/import">Add Multiple Products</a>
              <a class="dropdown-item" href="/app_setting/1">Global Settings</a>
              <a class="dropdown-item" href="/admin/orders">View Orders</a>
          </li>
      <% elsif current_user && !current_user.admin? %>
        <li class="nav-item">
          <%= link_to "My Cart", mycart_path, method: :get, :class => 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "My Orders", myorders_path, method: :get, :class => 'nav-link'%>
        </li>
      <% end %>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_session_path(current_user), method: :delete, :class => 'nav-link'%>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_up">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_in">Sign In</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Somsaem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application'%>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  </head>

  <body>
  
    <header>
      <%= render "layouts/nav" %>    
    </header>
    <br />
    <div class="main container">
    <p class="notice alert-primary text-center"><%= notice %></p>
    <p class="alert alert-warning text-center"><%= alert %></p>


    <%= yield %>
    </div>

    <footer>
      <%= render "layouts/footer" %>    
    </footer>
    <%# Bootstrap related %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>