config/routes.rb
Rails.application.routes.draw do

  
  resources :charges, only: [:new, :create]
  resources :line_items
  get '/products/:id/repairs', :to => 'products#repairs'
  get '/products/estimate_price', :to => 'products#estimate_price'
  get 'search/index'
  devise_for :users
  get 'user', to: 'users#show', as: 'myorders'
  resources :products
  resources :repairables
  resources :search, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'send/:id', to: 'pages#sendForm'
  get 'sales', to: 'sales#index'
  get '/admin/import', :to => 'admin#newimport'
  post '/admin/import', :to => 'admin#createimport'
  get '/admin/orders', :to => 'admin#orders'
  get '/admin/orders/:id', :to => 'admin#order'

  resources :app_setting, only: [:edit, :update, :show]

  get 'cart', to: 'carts#show', as: 'mycart'
  
  resources :orders, only: [:show]

end

app/models/app_setting.rb
class AppSetting < ApplicationRecord
    # The "singleton_guard" column is a unique column which must always be set to '0'
    # This ensures that only one AppSettings row is created
    validates_inclusion_of :singleton_guard, :in => [0]
    
    def self.instance
        first_or_create!(singleton_guard: 0)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
      current_item = line_items.find_by(product_id: product.id)
  
      if current_item
        current_item.increment(:quantity)
      else
        current_item = line_items.build(product_id: product.id)
      end
      current_item
    end
  
    def total_price
      line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  
  def total_price
    product.price * quantity.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    belongs_to :user, optional: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
require 'csv'
class Product < ApplicationRecord
    has_one_attached :productimage
    has_many :line_items
    has_many :order_items
    has_many :repairables
    accepts_nested_attributes_for :repairables

    # validates :name, :manufacturer, :model, :description, :quantity, :price, presence: true
    validates :model, uniqueness: true

    include PgSearch::Model
    pg_search_scope :search, against: [:name, :model, :manufacturer]

    before_destroy :not_referenced_by_any_line_item
    belongs_to :user, optional: true

    def self.import(file)
      CSV.foreach(file.path, headers:true) do |row|
        if !Product.find_by(model: row[2])
          product = Product.new
          product.name = row[0]
          product.manufacturer = row[1]
          product.model = row[2]
          product.description = row[3]
          product.quantity = row[4]
          product.price = row[5]
          product.is_repairable = row[6]
          product.base_price = row[7]
          product.save
        end
      end
    end

    private
  
     def not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line items present')
        throw :abort
      end
     end
end

app/models/repairable.rb
class Repairable < ApplicationRecord
    belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :destroy]

  def show
    if @cart.id == session[:cart_id]
      @products = []
      @cart.line_items.each do |item|
        @products.push(Product.find(item.product_id))
      end
      @total_price = @cart.total_price
      render :show
    else
      redirect_to root_path
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/app_setting_helper.rb
module AppSettingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/repairables_helper.rb
module RepairablesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<!--Section: Block Content-->
<section>

  <!--Grid row-->
  <div class="row">

    <!--Grid column-->
    <div class="col-lg-8">

      <!-- Card -->
      <div class="mb-3">
        <div class="pt-4 wish-list">

          <h5 class="mb-4">Cart (<%= @cart.line_items.length %>)</h5>
          <% if @cart.line_items.length > 0 %>
          <% @cart.line_items.each do |item| %>
            <% product = Product.find(item.product_id) %>
            <div class="row mb-4">
            <div class="col-md-5 col-lg-3 col-xl-3">
              <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
              <% if product.productimage.attached? %>
              <img src="<%=(url_for(product.productimage))%>" class="img-fluid">
              <% else %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/3/3b/Picture_Not_Yet_Available.png" class="img-fluid">
              <% end %>
              </div>
            </div>
            <div class="col-md-7 col-lg-9 col-xl-9">
              <div>
                <div class="d-flex justify-content-between">
                  <div>
                    <h5><%= product.name %></h5>
                    <p class="mb-3 text-muted text-uppercase small"><%= product.description %></p>
                    <p class="mb-2 text-muted text-uppercase small"><%= product.manufacturer %></p>
                    <p class="mb-3 text-muted text-uppercase small"><%= product.model %></p>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                  <%= button_to "Remove", line_item_path(item.id), method: :delete, :class => 'btn btn-sm btn-outline-secondary'%>
                  </div>
                  <p class="mb-0"><span><strong id="summary">$<%= '%.2f' % product.price %></strong></span></p class="mb-0">
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <% else %>
        <div>
        You have no items in your cart.  View <%= link_to "our products", products_path, method: :get, :class => 'py-2 d-none d-md-inline-block'%>.
        </div>
        <% end %>

        </div>
      </div>
      <!-- Card -->

      <!-- Card -->
      <div class="mb-3">
        <div class="pt-4">

          <h5 class="mb-4">We accept</h5>

          <img class="mr-2" width="45px"
            src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
            alt="Visa">
          <img class="mr-2" width="45px"
            src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
            alt="American Express">
          <img class="mr-2" width="45px"
            src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
            alt="Mastercard">
          <img class="mr-2" width="45px"
            src="https://mdbootstrap.com/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.png"
            alt="PayPal acceptance mark">
        </div>
      </div>
      <!-- Card -->

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-4">

      <!-- Card -->
      <div class="mb-3">
        <div class="pt-4">

          <h5 class="mb-3">The total amount of</h5>

          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
              Subtotal
              <span>$<%= '%.2f' % @total_price %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
              Free shipping
              <span>$0.00</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
              <div>
                <strong>Total</strong>
              </div>
              <span><strong>$<%= '%.2f' % @total_price %></strong></span>
            </li>
          </ul>
          <%= form_tag charges_path do %>
            <article>
              <% if flash[:error].present? %>
                <div id="error_explanation">
                  <p><%= flash[:error] %></p>
                </div>
              <% end %>
              <%= hidden_field_tag "amount", @total_price %>
            </article>
          
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-label="Pay with Stripe"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-description="Your Order"
                    data-amount="#{@total_price}"
                    data-locale="auto"></script>
          <% end %>
        </div>
      </div>
      <!-- Card -->

      <!-- Card -->
      <div class="mb-3">
        <div class="pt-4">

          <div class="collapse" id="collapseExample">
            <div class="mt-3">
              <div class="md-form md-outline mb-0">
                <input type="text" id="discount-code" class="form-control font-weight-light"
                  placeholder="Enter discount code">
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Card -->

    </div>
    <!--Grid column-->

  </div>
  <!-- Grid row -->

</section>
<!--Section: Block Content-->