config/routes.rb
Rails.application.routes.draw do

  
  resources :charges, only: [:new, :create]
  resources :line_items
  get '/products/:id/repairs', :to => 'products#repairs'
  get '/products/estimate_price', :to => 'products#estimate_price'
  get 'search/index'
  devise_for :users
  get 'user', to: 'users#show', as: 'myorders'
  resources :products
  resources :repairables
  resources :search, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'send/:id', to: 'pages#sendForm'
  get 'sales', to: 'sales#index'
  get '/admin/import', :to => 'admin#newimport'
  post '/admin/import', :to => 'admin#createimport'
  get '/admin/orders', :to => 'admin#orders'
  get '/admin/orders/:id', :to => 'admin#order'

  resources :app_setting, only: [:edit, :update, :show]

  get 'cart', to: 'carts#show', as: 'mycart'
  
  resources :orders, only: [:show]

end

app/models/app_setting.rb
class AppSetting < ApplicationRecord
    # The "singleton_guard" column is a unique column which must always be set to '0'
    # This ensures that only one AppSettings row is created
    validates_inclusion_of :singleton_guard, :in => [0]
    
    def self.instance
        first_or_create!(singleton_guard: 0)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
      current_item = line_items.find_by(product_id: product.id)
  
      if current_item
        current_item.increment(:quantity)
      else
        current_item = line_items.build(product_id: product.id)
      end
      current_item
    end
  
    def total_price
      line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  
  def total_price
    product.price * quantity.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    belongs_to :user, optional: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
require 'csv'
class Product < ApplicationRecord
    has_one_attached :productimage
    has_many :line_items
    has_many :order_items
    has_many :repairables
    accepts_nested_attributes_for :repairables

    # validates :name, :manufacturer, :model, :description, :quantity, :price, presence: true
    validates :model, uniqueness: true

    include PgSearch::Model
    pg_search_scope :search, against: [:name, :model, :manufacturer]

    before_destroy :not_referenced_by_any_line_item
    belongs_to :user, optional: true

    def self.import(file)
      CSV.foreach(file.path, headers:true) do |row|
        if !Product.find_by(model: row[2])
          product = Product.new
          product.name = row[0]
          product.manufacturer = row[1]
          product.model = row[2]
          product.description = row[3]
          product.quantity = row[4]
          product.price = row[5]
          product.is_repairable = row[6]
          product.base_price = row[7]
          product.save
        end
      end
    end

    private
  
     def not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line items present')
        throw :abort
      end
     end
end

app/models/repairable.rb
class Repairable < ApplicationRecord
    belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :repairs, :edit, :update, :destroy]
  before_action :authenticate_user!, :is_admin?, only: [:new, :create, :edit, :update, :destroy]

  def index
    if not params[:search].present?
      @products = Product.all
    else
      @products = Product.search(params[:search])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products, status: :ok }
    end
    # format.json { render json: @products, status: :ok}
  end

  # GET /products/estimate_price
  # GET /products.json
  def estimate_price
    product = Product.find_by(model: price_estimate_params[:model])
    setting = AppSetting.instance

    if product.base_price.present?
      price  = product.base_price
    else
      price = -1
    end
    
    if price_estimate_params[:previousRepairs].present?
      price -= price * setting[:previousRepairFactor] * Float(price_estimate_params[:previousRepairs])
    end
    if price_estimate_params[:wearLevel].present?
      price -= price * setting[:wearLevelFactor] * Float(price_estimate_params[:wearLevel])
    end
    if price_estimate_params[:serviceProviderLocked] == "true"
      price *= setting[:serviceProviderLockedFactor]
    end
    if price_estimate_params[:cloudLocked] == "true"
      price *= setting[:cloudLockedFactor]
    end
    if price_estimate_params[:bootupDefect] == "true"
      price *= setting[:bootupDefectFactor]
    end
    if price_estimate_params[:screenDefect] == "true"
      price *= setting[:screenDefectFactor]
    end

    #binding.pry
    price = price - price % 25 # Around to closest 25
    render json: price
  end

  def show
  end

  def repairs
    render :repairs
  end

  def new
    @product = Product.new
    @product.repairables.build
  end

  def edit
    @product.repairables.build
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :manufacturer, :model, :quantity, :price, :productimage, :is_repairable, :is_buying, :is_selling, :base_price, repairables_attributes: [:repair_name, :estimated_time, :repair_price])
    end

     def price_estimate_params
      # params.fetch(:product, {})
      params.permit(:model, :storage, :serviceProviderLocked, :wearLevel, :cloudLocked, :bootupDefect, :screenDefect, :previousRepairs)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/app_setting_helper.rb
module AppSettingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/repairables_helper.rb
module RepairablesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: product, local: true) do |form| %>
  <h3>Product Information</h3>
  <div class="form-group row">
    <%= form.label :name, "Name", :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-6">
      <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :description, "Description", :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-6">
      <%= form.text_area :description, placeholder: "Name", class: "form-control" %><br />
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :manufacturer, "Manufacturer", :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-6">
      <%= form.text_field :manufacturer, placeholder: "Name", class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :model, "Model", :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-6">
      <%= form.text_field :model, placeholder: "Name", class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :productimage, "Product Image", :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-6">
      <%= form.file_field :productimage, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-2">Do you want to...</div>
    <div class="col-sm-10">
      <div class="form-check">

        <%= form.check_box :is_selling, class: "form-check-input" %>
        <label class="form-check-label" for="gridCheck1">
          ...sell the product?
        </label>
      </div>
      <div class="form-check">
        <%= form.check_box :is_buying, class: "form-check-input" %>
        <label class="form-check-label" for="gridCheck1">
          ...buy the product?
        </label>
      </div>
      <div class="form-check">
        <%= form.check_box :is_repairable, class: "form-check-input" %>
        <label class="form-check-label" for="gridCheck1">
          ...repair the product?
        </label>
      </div>
    </div>
  </div>
  <h4>Sell</h4>
  <div class="form-group row">
    <%= form.label :quantity, "Quantity", :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-6">
      <%= form.text_field :quantity, placeholder: "Name", class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :price, "Price", :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-6">
      <%= form.text_field :price, placeholder: "Name", class: "form-control" %>
    </div>
  </div>
  <h4>Buy</h4>
  <div class="form-group row">
    <%= form.label :base_price, "Base Buy Price", :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-6">
      <%= form.text_field :base_price, placeholder: "Name", class: "form-control" %>
    </div>
  </div>
  <h4>Repair</h4>
  <%= form.fields_for :repairables do |repairable_attributes|%>
    <div class="form-group row">
      <%= repairable_attributes.label :repair_name, "Name", :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= repairable_attributes.text_field :repair_name, placeholder: "Name", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= repairable_attributes.label :estimated_time, "Estimated Time to Repair (hours)", :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= repairable_attributes.text_field :estimated_time, placeholder: "Name", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= repairable_attributes.label :repair_price, "Price", :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-6">
        <%= repairable_attributes.text_field :repair_price, placeholder: "Name", class: "form-control" %>
      </div>
    </div>
  <% end %>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/products/_product.html.erb
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <% if product.productimage.attached? %>
            <img class="card-img-top" src="<%=(url_for(product.productimage))%>" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1728a7d1574%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1728a7d1574%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.7109375%22%20y%3D%22120.15%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
        <% else %>
            <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1728a7d1574%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1728a7d1574%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.7109375%22%20y%3D%22120.15%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
        <% end %>
            <div class="card-body">
            <p class="card-text"> <%= product.name %> </p>
            <p class="card-text"> Description: <%= product.description %> </p>
            <% if product.quantity && (product.quantity > 0) %>
            <p class="card-text"> <%= product.quantity %> In Stock </p>
            <% else %>
            <p class="card-text"> Out of Stock </p>
            <% end %>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <% if product.quantity && (product.quantity > 0) %>
                    <%= button_to 'Add to cart', line_items_path(product_id: product.id), class: 'btn btn-sm btn-outline-secondary mr-1'%>
                    <% end %>
                    <%= button_to "View More", product_path(product), method: :get, :class => 'btn btn-sm btn-outline-secondary mr-1'%>
                    <% if current_user && current_user.admin? %>
                    <%= button_to "Edit", edit_product_path(product), method: :get, :class => 'btn btn-sm btn-primary mr-1'%>
                    <% end %>
                </div>
            <small class="text-muted">$<%= '%.2f' % product.price.to_i %> </small>
            </div>
        </div>
    </div>
</div>

app/views/products/_search.html.erb
<section class="row">
    <h2>Search for products</h2>
</section>

<div class="row">
    <%= form_tag products_path, url: products_path, method: :get do %>
        <%= text_field_tag :search %>
        <%=submit_tag 'search', name: nil %>
    <% end %>
</div> 

<br />

<% unless @products.nil? %>
  <% if @products.empty? %>
    <div class="row"> 
        <h2>No products found matching your query.</h2>
    </div>
  <% else %>
    <div class="row"> 
        <%= render @products %>
    </div>
    <% end %>
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>
<br />
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<%= render "search" %>

<%# <div class="row">  %>
<%# <%= render @products %>
<%# <%= render partial: "productCard", collection: @products %> 
<%# </div> %>
<br> -->

<div id="react-container">
    <%= javascript_pack_tag 'indexProduct' %>
    </div>

app/views/products/new.html.erb
<h2>New Product</h2>
<small class="text-muted">Want to add many new products at once? <a href="/admin/import">Try uploading in bulk instead.</a></small> 
<br />
<br />
<%= render 'form', product: @product %>

app/views/products/repairs.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 product_img">
            <% if @product.productimage.attached? %>
            <img src="<%=(url_for(@product.productimage))%>" class="img-fluid">
            <% else %>
            <img src="https://upload.wikimedia.org/wikipedia/commons/3/3b/Picture_Not_Yet_Available.png" class="img-fluid">
            <% end %>
        </div>
        <div class="col-md-6 product_content">
            <h4><%= @product.name %></h4>
            <p><%= @product.description %></p>
            <div class="space-ten"></div>
            <br />

            <% @product.repairables.each do |repair| %>
                <div class="row">
                    <div class="col-md-6">
                        <p><%= repair.repair_name %> (<%= repair.estimated_time %> Hours) - <%= repair.repair_price %> SEK </p>
                    </div>
                    <div class="col-md-6">
                        <div>
                            <%= button_to "Add repair", :class => 'btn btn-sm btn-outline-secondary'%>
                        </div>
                    </div>
                </div>
            <% end %>    
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <%= button_to "Back", repairables_path, method: :get, :class => 'btn btn-secondary'%>
        </div>
        <div class="col-md-6">
            <%= button_to "Next", send_path(@product), method: :get, :class => 'btn btn-primary'%>
        </div>
    </div>
</div>

<% if is_admin? %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<% end %>

app/views/products/show.html.erb
<div class="container">
<div class="row">
    <div class="col-md-6 product_img">
        <% if @product.productimage.attached? %>
        <img src="<%=(url_for(@product.productimage))%>" class="img-fluid">
        <% else %>
        <img src="https://upload.wikimedia.org/wikipedia/commons/3/3b/Picture_Not_Yet_Available.png" class="img-fluid">
        <% end %>
    </div>
    <div class="col-md-6 product_content">
        <h4><%= @product.name %></h4>
        <p><%= @product.description %></p>
        <% if @product.quantity && (@product.quantity > 0) %>
        <p><%= @product.quantity %> In Stock</p>
        <h3 class="cost"><span class="glyphicon glyphicon-usd">$<%= '%.2f' % @product.price.to_i %></span><small class="pre-cost"><span class="glyphicon glyphicon-usd"></span></small></h3>
        
        <div class="space-ten"></div>
        <br />
        <div class="btn-ground">
            <%= button_to 'Add to cart', line_items_path(product_id: @product.id), class: 'btn btn-primary' %>
        </div>
        <% else %>
        <p>Out of Stock</p>
        <% end %>
    </div>
</div>
</div>

<% if is_admin? %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<% end %>